export default () => [
  'redux saga tutorial',
  'fetch api with react',
  'reactDnd with Redux?',
  'authentication with react, react router, redux, redux saga',
  'node with middleware, authentication?',
  'Oauth',
  'node on https with express',
  'react-native',
  'node School',
  'machine learning with different source',
  'find jobs',
  'bookmark backlogs',
  'try out currying? especially in node',
];
